/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Logincontroller;
import java.sql.ResultSet;
import java.sql.Statement;
import model.DBConnection;

/**
 *
 * @author VENUSHA
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        loginBtn.setEnabled(false);
        createNewBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usNameTF = new javax.swing.JTextField();
        passwordPF = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fpasswordL = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        createNewBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("LETSREAD ONLINE LIBRARY");

        usNameTF.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        usNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usNameTFActionPerformed(evt);
            }
        });
        usNameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usNameTFKeyReleased(evt);
            }
        });

        passwordPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordPFActionPerformed(evt);
            }
        });
        passwordPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordPFKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel4.setText("User Name");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel5.setText("Password");

        fpasswordL.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        fpasswordL.setForeground(new java.awt.Color(0, 51, 204));
        fpasswordL.setText("Fogot password?");
        fpasswordL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fpasswordLMouseClicked(evt);
            }
        });

        loginBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 0, 102));
        loginBtn.setText("Login");
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtnMousePressed(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        loginBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loginBtnKeyReleased(evt);
            }
        });

        createNewBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        createNewBtn.setForeground(new java.awt.Color(255, 0, 102));
        createNewBtn.setText("Create New");
        createNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fpasswordL, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordPF, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createNewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordPF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(fpasswordL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createNewBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usNameTFActionPerformed

    private void fpasswordLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fpasswordLMouseClicked
        // TODO add your handling code here:
        login.getFrames()[0].dispose();
        new FogotPassword().setVisible(true);
    }//GEN-LAST:event_fpasswordLMouseClicked

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        Logincontroller.login(usNameTF.getText(),passwordPF.getText());
      //  clearField();
    }//GEN-LAST:event_loginBtnActionPerformed

    private void createNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewBtnActionPerformed
        // TODO add your handling code here:
        loginBtn.setEnabled(false);
        createNewBtn.setEnabled(false);
        Logincontroller.login1(usNameTF.getText(),passwordPF.getText());
        clearField();
    }//GEN-LAST:event_createNewBtnActionPerformed

    private void usNameTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usNameTFKeyReleased
        // TODO add your handling code here:
        if(usNameTF.getText().equals("") || passwordPF.getText().equals("")){
            loginBtn.setEnabled(false); 
            createNewBtn.setEnabled(false);
        }else{
        String h="Hello";
            String u=usNameTF.getText();
            String p=passwordPF.getText();
            String user="";
            String pw="";
            try{
                ResultSet r=null;
                Statement stmt=DBConnection.getStatementConnection();
                r=stmt.executeQuery("SELECT * FROM login WHERE username='"+u+"' AND password='"+p+"'");
                if(r.next()){
                    user=r.getString("username");
                    pw=r.getString("password");
                    h="";
                }
            }catch(Exception e){
                e.printStackTrace();
            }
            if(h.equals("")){
            loginBtn.setEnabled(true); 
            createNewBtn.setEnabled(false);
        }else{
            loginBtn.setEnabled(false); 
            createNewBtn.setEnabled(true);    
            }}
    }//GEN-LAST:event_usNameTFKeyReleased

    private void passwordPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordPFKeyReleased
        // TODO add your handling code here:
        if(usNameTF.getText().equals("") || passwordPF.getText().equals("")){
            loginBtn.setEnabled(false); 
            createNewBtn.setEnabled(false);
        }else{
        String h="Hello";
            String u=usNameTF.getText();
            String p=passwordPF.getText();
            String user="";
            String pw="";
            try{
                ResultSet r=null;
                Statement stmt=DBConnection.getStatementConnection();
                r=stmt.executeQuery("SELECT * FROM login WHERE username='"+u+"' AND password='"+p+"'");
                if(r.next()){
                    user=r.getString("username");
                    pw=r.getString("password");
                    h="";
                }
            }catch(Exception e){
                e.printStackTrace();
            }
            if(h.equals("")){
            loginBtn.setEnabled(true); 
            createNewBtn.setEnabled(false);
        }else{
            loginBtn.setEnabled(false); 
            createNewBtn.setEnabled(true);    
            }}
    }//GEN-LAST:event_passwordPFKeyReleased

    private void loginBtnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginBtnKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnKeyReleased

    private void loginBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnMousePressed

    private void passwordPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordPFActionPerformed
     public void clearField(){
        usNameTF.setText("");
        passwordPF.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createNewBtn;
    private javax.swing.JLabel fpasswordL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordPF;
    private javax.swing.JTextField usNameTF;
    // End of variables declaration//GEN-END:variables
}
